% Script to convert SiMREPS data to the OpenFRET format

%% User-defined metadata

title = '20250204_AJB_2: miRNA probe test';
description = 'Short probe test with miR-16 and miR-141';
experiment_type = 'SiMREPS';
authors = {'Alex Johnson-Buck'};
institution = 'The University of Michigan';
date = '2025-02-04';
experiment_id = '20250204_AJB_2'; % Example metadata
buffer_conditions = '4X PBS';
temperature = '28 C';
microscope = 'Olympus IX83 (Laser Bay 2)';
detector = 'Hamamatsu Orca Fusion EMCCD';
objective = '60X 1.5 NA';
excitation_wavelength = 640;

%% Settings

% Compress to zip file (recommend setting to 'true')
compress = true;

%% Run conversion

simreps2openfret('title',title,...
        'description',description,...
        'experiment_type',experiment_type,...
        'authors',authors,...
        'institution',institution,...
        'date',date,...
        'experiment_id',experiment_id,...
        'buffer_conditions',buffer_conditions,...
        'temperature',temperature,...
        'microscope',microscope,...
        'detector',detector,...
        'objective',objective,...
        'excitation_wavelength',excitation_wavelength);