%% User-defined options and metadata - modify this for each experiment

% Metadata
title = '(Experiment name goes here)';
description = '(Short description of instrument goes here)';
experiment_type = '(Experiment date goes here)';
authors = {'(Author of experiment)'};
institution = 'The University of Michigan';
date = 'YYYY-MM-DD';
experiment_id = 'YYYYMMDD_ABC_1'; % Recommended format: year_initials_experiment
buffer_conditions = '4X PBS';
temperature = '28 C';
microscope = 'Olympus IX83 (Laser Bay 2)';
detector = 'Hamamatsu Orca Fusion EMCCD';
objective = '60X 1.5 NA';
excitation_wavelength.channel1 = 532; % In nanometers
excitation_wavelength.channel2 = 640; % In nanometers

options.use_channel1 = true; % true = include channel 1 (green/donor) in OpenFRET; false = omit
options.use_channel2 = true; % true = include channel 2 (red/acceptor) in OpenFRET; false = omit

options.donor_crosstalk = 0.09; % (For 2-channel traces files): crosstalk of donor into acceptor channel, as fraction of donor-channel signal

filenames = getFileNames();

%% Run conversion to OpenFRET
convertFiles(filenames,'title',title,...
        'description',description,...
        'experiment_type',experiment_type,...
        'authors',authors,...
        'institution',institution,...
        'date',date,...
        'experiment_id',experiment_id,...
        'buffer_conditions',buffer_conditions,...
        'temperature',temperature,...
        'microscope',microscope,...
        'detector',detector,...
        'objective',objective,...
        'excitation_wavelength',excitation_wavelength,...
        'options',options);